version: '3.5'
volumes:
  db_data:
  app_data:
services:
  db:
    restart: always
    build:
      context: ../
      dockerfile: docker/postgres/Dockerfile
    image: manolo/manolo_db
    shm_size: '1gb'
    volumes:
      - db_data:/srv/postgresql/data/
    expose:
      - '5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    command: postgres
      -c max_connections=1000
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    image: manolo/manolo_app
    command: |
      /wait_for_it.sh db:5432 -t 0 -- gunicorn
      --workers 5
      --threads 2
      --timeout 3600
      --max-requests 200
      --max-requests-jitter 50
      --graceful-timeout 30
      --worker-class=manolo.gunicorn_worker.UvicornWorkerLifeSpanOff
      --log-level debug
      --error-logfile=-
      --preload
      -b 0.0.0.0:8000 manolo.asgi
    volumes:
      - app_data:/data
      - /logs
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'manolo.settings.production'
  nginx:
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    image: manolo/manolo_nginx
    volumes:
      - app_data:/data
    ports:
      - "4082:80"
      - "4432:443"
    depends_on:
      - app
  celery_worker:
    restart: always
    image: manolo/manolo_app
    command: /wait_for_it.sh redis:6379
      --timeout=0 --
      /wait_for_it.sh db:5432
      --timeout=0 -- celery
      --app=manolo worker
      --hostname=default@%h
      --loglevel=info
      --concurrency=2
      --queues=default
      --beat
    depends_on:
      - redis
      - db
    environment:
      C_FORCE_ROOT: 'True'
      DJANGO_SETTINGS_MODULE: 'manolo.settings.production'
    volumes:
      - app_data:/data
  redis:
    restart: always
    image: redis:7.0.10
    command: redis-server --appendonly yes
    volumes:
      - app_data:/data
    expose:
      - '6379'
  cron:
    restart: always
    build:
      context: ../
      dockerfile: docker/cron/Dockerfile
    image: manolo/manolo_app
    volumes:
      - app_data:/data
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'manolo.settings.production'
